- name: Create Prometheus group
  group:
    name: "{{ prometheus_group }}"
    state: present

- name: Create Prometheus user
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    create_home: no
    shell: /sbin/nologin

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
  loop:
    - "{{ prometheus_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"

- name: Extract Prometheus
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Install Prometheus binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    mode: "0755"
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Install Prometheus config
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_file }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0644"
  notify: Restart Prometheus

- name: Install systemd service
  template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
    mode: "0644"
  notify: Restart Prometheus

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes
